package graphics

import (
	"github.com/go-gl/gl/v4.1-core/gl"
	"github.com/go-gl/mathgl/mgl32"
	"github.com/mlynam/project-june/engine"
)

// Camera provides data required to setup a scene camera
type Camera struct {
	engine.Object
	graphics                              engine.Graphics
	FieldOfView, ZFar, ZNear, AspectRatio float32
	view, projection                      [16]float32
}

// NewCamera with given graphics engine
func NewCamera(g engine.Graphics) *Camera {
	return &Camera{
		graphics: g,
	}
}

// SetTransformations sets the `camera` and `projection` uniform mat4
//  values in the shader program
func (c *Camera) SetTransformations() {
	index, ok := c.graphics.Uniform("view")
	if ok {
		c.view = c.View()
		gl.UniformMatrix4fv(index, 1, false, &c.view[0])
	}

	index, ok = c.graphics.Uniform("projection")
	if ok {
		c.projection = c.Projection()
		gl.UniformMatrix4fv(index, 1, false, &c.projection[0])
	}
}

// View returns transformation matrix from the point of view of the camera
func (c *Camera) View() [16]float32 {
	eye := c.Position()
	center := mgl32.Vec3{}
	up := mgl32.Vec3{0, 1, 0}
	return mgl32.LookAtV(eye, center, up)
}

// Projection returns the projection matrix generated by the camera
func (c *Camera) Projection() [16]float32 {
	return mgl32.Perspective(c.FieldOfView, c.AspectRatio, c.ZNear, c.ZFar)
}
